package com.jack.appnews.storage.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jack.appnews.bean.DBCateBean;
import com.jack.appnews.bean.DBNewsBean;

import com.jack.appnews.storage.db.DBCateBeanDao;
import com.jack.appnews.storage.db.DBNewsBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBCateBeanDaoConfig;
    private final DaoConfig dBNewsBeanDaoConfig;

    private final DBCateBeanDao dBCateBeanDao;
    private final DBNewsBeanDao dBNewsBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBCateBeanDaoConfig = daoConfigMap.get(DBCateBeanDao.class).clone();
        dBCateBeanDaoConfig.initIdentityScope(type);

        dBNewsBeanDaoConfig = daoConfigMap.get(DBNewsBeanDao.class).clone();
        dBNewsBeanDaoConfig.initIdentityScope(type);

        dBCateBeanDao = new DBCateBeanDao(dBCateBeanDaoConfig, this);
        dBNewsBeanDao = new DBNewsBeanDao(dBNewsBeanDaoConfig, this);

        registerDao(DBCateBean.class, dBCateBeanDao);
        registerDao(DBNewsBean.class, dBNewsBeanDao);
    }
    
    public void clear() {
        dBCateBeanDaoConfig.getIdentityScope().clear();
        dBNewsBeanDaoConfig.getIdentityScope().clear();
    }

    public DBCateBeanDao getDBCateBeanDao() {
        return dBCateBeanDao;
    }

    public DBNewsBeanDao getDBNewsBeanDao() {
        return dBNewsBeanDao;
    }

}
