package com.jack.appnews.storage.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.jack.appnews.bean.DBCateBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "new_cate".
*/
public class DBCateBeanDao extends AbstractDao<DBCateBean, Void> {

    public static final String TABLENAME = "new_cate";

    /**
     * Properties of entity DBCateBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Cate_id = new Property(0, int.class, "cate_id", false, "CATE_ID");
        public final static Property Cate_name = new Property(1, String.class, "cate_name", false, "CATE_NAME");
    };


    public DBCateBeanDao(DaoConfig config) {
        super(config);
    }
    
    public DBCateBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"new_cate\" (" + //
                "\"CATE_ID\" INTEGER NOT NULL ," + // 0: cate_id
                "\"CATE_NAME\" TEXT);"); // 1: cate_name
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"new_cate\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DBCateBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getCate_id());
 
        String cate_name = entity.getCate_name();
        if (cate_name != null) {
            stmt.bindString(2, cate_name);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DBCateBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getCate_id());
 
        String cate_name = entity.getCate_name();
        if (cate_name != null) {
            stmt.bindString(2, cate_name);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public DBCateBean readEntity(Cursor cursor, int offset) {
        DBCateBean entity = new DBCateBean( //
            cursor.getInt(offset + 0), // cate_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // cate_name
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DBCateBean entity, int offset) {
        entity.setCate_id(cursor.getInt(offset + 0));
        entity.setCate_name(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(DBCateBean entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(DBCateBean entity) {
        return null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
